# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
# are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

url    : "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

title      : PettingZoo
email      : jkterry@gmail.com #this is also the email contact forms will go to
description: "Multi-Agent Reinforcement Learning Environments"
author     : Your Name
copyright  : Farama Foundation
logo:     #optional, defaults to site title
  path: /assets/img/PettingZoo_White.svg
  height: 100 #height in px, defaults to 52px

analytics:
  google: #Google Analytics tracking code here

collections:
  portfolio:

markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      layout: docu
      is_parallel: "True"
  -
    scope:
      path: "classic"
    values:
      is_parallel: "false" # overrides previous default layout
